Modified the home page (app/page.tsx) to include Mata Tags
SeattleColleges/nsc-events-nextjs pull request #263
Opened 2024-04-18 20:35 UTC by gitbiruk2010

This is a pull request!

Please use the following format for the title:
< https://github.com/SeattleColleges/nsc-events-nextjs/tree/main > _ < sprint 5 Planning> _ < #262  > _ < Meta Data >

Please fill out this description with the following:
Resolves <issue #262 >
Description of what this pull request is for: Adding Meta Tags, Meta Images, and SEO to the NSC Event Next.js Home page app/page.tsx

Screenshots:
![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/103274295/5174021b-5890-4cdd-87ea-3ddd64642874)

![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/103274295/175010a1-6085-4b01-ba9e-aea017360a92)

Enable auto-merge (squash) at the bottom of the page.

2024-04-19 04:46 UTC, nwm516 commented
It looks like your meta data is within the appropriate head element. There seems to be no spelling errors, missing parentheses, or closing tags. LGTM.

2024-04-19 05:02 UTC, miqo1385 commented
still learning a bit about this, but it looks good to me.

2024-04-22 20:34 UTC, taylorpapke reviewed
I'm not familiar with how to test this. Should I be able to check the page source and view these tags when I run your branch?

2024-04-23 17:51 UTC, brinkbrink approved these changes
I see that the meta tags have been added. I would like the product owner @heosman to sign off on the meta tags, unless you got this information from the product owner beforehand.

I also want to point out that there is a lot more to SEO that I would like you to research and implement. Take a look through Google's [Search Engine Optimization (SEO) Starter Guide](https://developers.google.com/search/docs/fundamentals/seo-starter-guide) and checklists like [this](https://backlinko.com/seo-checklist) to start. 

I have modified the issue and user story related to this pull request to reflect its incomplete status. Please reach out to me on Slack or respond to my comment here if you have any questions.

2024-04-23 17:52 UTC, brinkbrink submitted a review, later dismissed
@heosman Can you please review these tags?

2024-04-23 17:52 UTC, brinkbrink commented
I see that the meta tags have been added. I would like the product owner @heosman to sign off on the meta tags, unless you got this information from the product owner beforehand.

I also want to point out that there is a lot more to SEO that I would like you to research and implement. Take a look through Google's [Search Engine Optimization (SEO) Starter Guide](https://developers.google.com/search/docs/fundamentals/seo-starter-guide) and checklists like [this](https://backlinko.com/seo-checklist) to start. 

I have modified the issue and user story related to this pull request to reflect its incomplete status. Please reach out to me on Slack or respond to my comment here if you have any questions.

2024-04-23 17:53 UTC, brinkbrink commented
> I'm not familiar with how to test this. Should I be able to check the page source and view these tags when I run your branch?

Hey @taylorpapke you can only view these tags in the file itself. I guess you could test the branch by making sure the tags don't disrupt any functionality but I feel that this is pretty straightforward and probably doesn't need that.

2024-04-23 19:46 UTC, taylorpapke approved these changes

2024-04-23 20:32 UTC, gitbiruk2010 commented
I am working on the SEO and I will do a PR on that as well.

On Tue, Apr 23, 2024, 10:51 AM E. Brink ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> I see that the meta tags have been added. I would like the product owner
> @heosman <https://github.com/heosman> to sign off on the meta tags,
> unless you got this information from the product owner beforehand.
>
> I also want to point out that there is a lot more to SEO that I would like
> you to research and implement. Take a look through Google's Search Engine
> Optimization (SEO) Starter Guide
> <https://developers.google.com/search/docs/fundamentals/seo-starter-guide>
> and checklists like this <https://backlinko.com/seo-checklist> to start.
>
> I have modified the issue and user story related to this pull request to
> reflect its incomplete status. Please reach out to me on Slack or respond
> to my comment here if you have any questions.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SeattleColleges/nsc-events-nextjs/pull/263#pullrequestreview-2017913943>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYT5ON4KDTII2YJFDF4KBZ3Y62NSFAVCNFSM6AAAAABGN7QJFGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMJXHEYTGOJUGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-04-23 20:36 UTC, brinkbrink commented
Thanks, @gitbiruk2010 !

2024-04-24 06:14 UTC, heosman requested changes
@gitbiruk2010 I can see the changes made in the home page file when I pull the branch on my IDE, but when I run the app, my browser title still says "Create Next App". Should it not be titled "North Seattle College Events" now? I don't see this title or those meta tags in the head when I use dev tools. It seems that the title and meta tags might be overridden by the metadata variable in layout.tsx.

@taylorpapke @brinkbrink Would we not be able to test the PR this way?

2024-04-24 08:08 UTC, gitbiruk2010 commented
Haven't checked if the changes I made are merged to the main. If it is, you
should see the tags added. You might wanna check if your pr is  the latest.
The changes made doesn't affect the the behavior of the web parts so it may
be another issue. Let me know what you find.

On Tue, Apr 23, 2024, 11:14 PM hanan o. ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @gitbiruk2010 <https://github.com/gitbiruk2010> I can see the changes
> made in the home page file when I pull the branch on my IDE, but when I run
> the app, my browser title still says "Create Next App". Should it not be
> titled "North Seattle College Events" now? I don't see the title or meta
> tags when I use dev tools. It seems that it might be overridden by the
> metadata variable in layout.tsx.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SeattleColleges/nsc-events-nextjs/pull/263#pullrequestreview-2018934628>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYT5ON6GJ3UKWOJLZBV46FTY65EVTAVCNFSM6AAAAABGN7QJFGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMJYHEZTINRSHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-24 16:33 UTC, brinkbrink commented
> @gitbiruk2010 I can see the changes made in the home page file when I pull the branch on my IDE, but when I run the app, my browser title still says "Create Next App". Should it not be titled "North Seattle College Events" now? I don't see this title or those meta tags in the head when I use dev tools. It seems that the title and meta tags might be overridden by the metadata variable in layout.tsx.
> 
> @taylorpapke @brinkbrink Would we not be able to test the PR this way?

Yep, that makes sense.

2024-04-24 16:45 UTC, brinkbrink commented
> @gitbiruk2010 I can see the changes made in the home page file when I pull the branch on my IDE, but when I run the app, my browser title still says "Create Next App". Should it not be titled "North Seattle College Events" now? I don't see this title or those meta tags in the head when I use dev tools. It seems that the title and meta tags might be overridden by the metadata variable in layout.tsx.
> 
> @taylorpapke @brinkbrink Would we not be able to test the PR this way?

No, not really, because the "Create React App" title is actually an issue with the HTML <title> tag. What is edited here is the metadata for a title, which is what web crawlers (what search engines use) will pick up on. We should definitely edit that <title> tag, though.

2024-04-24 17:03 UTC, brinkbrink commented
But now that I'm looking closer, I see that this tag was also edited. When I run this branch locally neither the meta tags or title are changed:

<img width="544" alt="Screenshot 2024-04-24 at 9 59 14 AM" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/80282265/2633b35b-ec1f-4557-bb0e-5c3c17ffccaa">

Some suggestions:

1. "use client" could be interfering: https://www.reddit.com/r/nextjs/comments/11fjnpq/new_metadata_support_and_use_client/
2. We should be creating a Head component and then importing that: https://nextjs.org/docs/app/building-your-application/optimizing/metadata
3. We could also use a metadata object: https://nextjs.org/docs/app/building-your-application/optimizing/metadata

Thanks for the reminder that we should always pull the branch and test locally. @heosman @taylorpapke

2024-04-24 18:51 UTC, tinpham5614 commented
I have a question:
Should metadata be implemented in the layout.tsx as in the screenshot here? 
![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/72054441/4a916152-8922-4920-8469-7c4654ab64a9)

Resources:
https://nextjs.org/learn/dashboard-app/adding-metadata#page-title-and-descriptions

2024-04-24 19:49 UTC, brinkbrink commented
> I have a question: Should metadata be implemented in the layout.tsx as in the screenshot here? ![image](https://private-user-images.githubusercontent.com/72054441/325346114-4a916152-8922-4920-8469-7c4654ab64a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODgzNDUsIm5iZiI6MTcxMzk4ODA0NSwicGF0aCI6Ii83MjA1NDQ0MS8zMjUzNDYxMTQtNGE5MTYxNTItODkyMi00OTIwLTg0NjktN2M0NjU0YWI2NGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE5NDcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYWI3MTZiZWNjOTc1ODY0MGU4MmZmNzI3MGE1MzY1NDc4ZGM0ZWViYzMzODc2MjVjOWU3MzgxZGZlYWI4NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1QWy2oAULqnt7nFztmBifIcKB2tD8SNiyNGulsetFF4)
> 
> Resources: https://nextjs.org/learn/dashboard-app/adding-metadata#page-title-and-descriptions

Yes, @tinpham5614, thank you for finding the metadata object. This is definitely the biggest issue here. The metadata object should be edited. For more information, @gitbiruk2010, reference the link in my previous comment.

2024-04-25 03:10 UTC, gitbiruk2010 commented
> I have a question: Should metadata be implemented in the layout.tsx as in the screenshot here? ![image](https://private-user-images.githubusercontent.com/72054441/325346114-4a916152-8922-4920-8469-7c4654ab64a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMTQ4NjIsIm5iZiI6MTcxNDAxNDU2MiwicGF0aCI6Ii83MjA1NDQ0MS8zMjUzNDYxMTQtNGE5MTYxNTItODkyMi00OTIwLTg0NjktN2M0NjU0YWI2NGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDAzMDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNGFjNWQyMzE3ZDAyM2JmNzFjNzAzOTI2N2Q2MTc0Njk4ODQ5ODk3ZDkzY2RhYTFiYmUzNDFlMTY0NWI1NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V2myL9w1FTgxUc4KzV82AglXp3OgItKnjIxJl1t6cQs)
> 
> Resources: https://nextjs.org/learn/dashboard-app/adding-metadata#page-title-and-descriptions

You are Correct! i had the update implemented on page.tsx. I have made a correction and i will do a new pr. Thanks for catching that!

2024-04-25 03:43 UTC, gitbiruk2010 commented
![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/103274295/77b5297e-4023-406d-be53-b9d2e3364c50)

2024-04-25 03:46 UTC, Diego-Cano commented
Nice one on the SEO front for the app/page.tsx! Always a fan of seeing those meta elements getting improved. The screenshots are looking sharp, too!

Once we get this live, I’m keen to see how it’ll play out with our traffic stats. For anyone keen to brush up on SEO, Moz has some solid articles, and Search Engine Journal is like an encyclopedia for this stuff. 

Here are a couple of useful links:
https://www.searchenginejournal.com/
https://moz.com/blog/category/search-engines

2024-04-25 16:39 UTC, brinkbrink reviewed
Thank you for moving this to layout.tsx but it looks like the metadata object was not edited like I recommended above. It also appears that the meta properties in the head tag are pulling attributes from the metadata object, but those attributes do not exist. 

So when I test this branch locally there is no title and I can't find the metadata when inspecting the page:

<img width="1075" alt="Screenshot 2024-04-25 at 9 37 01 AM" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/80282265/b0dc4bb8-1eaa-461d-ba4d-232beece12ac">

I just edited this branch locally to show you what I'm saying. I deleted the head tag and edited the metadata object:

<img width="529" alt="Screenshot 2024-04-25 at 9 32 52 AM" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/80282265/c662be1b-3fac-4699-940b-652b3ecf97e2">

And now you can see a title for the page at the top of the browser window and the metadata I edited/added when inspecting the page.

<img width="1054" alt="Screenshot 2024-04-25 at 9 29 12 AM" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/80282265/3332b5e6-1ba0-41a6-ae6e-61f0ce47b13f">

Hope this clears things up.

2024-04-25 16:40 UTC, brinkbrink requested changes
Thank you for moving this to layout.tsx but it looks like the metadata object was not edited like I recommended above. It also appears that the meta properties in the head tag are pulling attributes from the metadata object, but those attributes do not exist. 

So when I test this branch locally there is no title and I can't find the metadata when inspecting the page:

<img width="1075" alt="Screenshot 2024-04-25 at 9 37 01 AM" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/80282265/b0dc4bb8-1eaa-461d-ba4d-232beece12ac">

I just edited this branch locally to show you what I'm saying. I deleted the head tag and edited the metadata object:

<img width="529" alt="Screenshot 2024-04-25 at 9 32 52 AM" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/80282265/c662be1b-3fac-4699-940b-652b3ecf97e2">

And now you can see a title for the page at the top of the browser window and the metadata I edited/added when inspecting the page.

<img width="1054" alt="Screenshot 2024-04-25 at 9 29 12 AM" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/80282265/3332b5e6-1ba0-41a6-ae6e-61f0ce47b13f">

Hope this clears things up.

2024-04-25 16:44 UTC, brinkbrink commented on app/page.tsx
This should no longer be edited if we are using layout.tsx

2024-04-26 02:59 UTC, gitbiruk2010 commented
![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/103274295/e6c248bd-deec-468b-96fe-d175c3ffa08e)

2024-04-26 03:00 UTC, gitbiruk2010 commented
![NSC Events](https://github.com/SeattleColleges/nsc-events-nextjs/assets/103274295/d33f9580-b180-4806-a81b-b26919e71a52)

2024-05-01 07:58 UTC, taylorpapke commented
@brinkbrink @heosman Can you both please re-review this, see if the requested changes have been made and approve if they have?

@gitbiruk2010 You will also have to resolve the merge conflicts on this PR.

2024-05-01 16:33 UTC, brinkbrink requested changes
<img width="547" alt="Screenshot 2024-05-01 at 9 25 36 AM" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/80282265/b7503834-ed01-48b2-b2bc-dcb173129824">

I see the title is working. That's great! But the rest of the metadata seems to still be incorrect. From my research on this issue I do not see a need for any metadata living in the <Head> tag because we have a metadata object doing this already. 

https://nextjs.org/learn/dashboard-app/adding-metadata
https://nextjs.org/docs/app/building-your-application/optimizing/metadata

2024-05-02 02:50 UTC, heosman reviewed
@gitbiruk2010 Like @brinkbrink mentioned, I can now see the title properly but the other metadata tags, such as the description, are still not visible to me in the browser.

Similar to the title metadata tag in this screenshot below, the other metadata tags you added, such as the description, should also be replacing the current metadata tags in the metadata object in the layout.tsx file.
<img width="419" alt="image" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/77591083/d56ccc94-4136-4a57-afa4-8769f451346d">

Because of the existing metadata object in layout.tsx, the head element in the page.tsx file (in the app directory) is redundant, and can be removed.

2024-05-02 23:55 UTC, JoyZhang2023 requested changes
Looks good to me. All meta tags are in correct format with proper module imported. 
One thing may need revisit is that the page.tsx inherited the meta tag from layout.tsx. Thus the home page title is showing "NSC Events" as noted in layout.tsx instead of "North Seattle College Events" in page.tsx. 
![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/137982978/52292bd3-1db9-4bc1-ba8b-ca5c14568332)

2024-05-08 02:48 UTC, taylorpapke commented
@gitbiruk2010 @brinkbrink @JoyZhang2023 What is the status for this PR? Is it reasonable to expect that we will be able to make the necessary changes, approve and resolve the conflicts here? If not, what course of action should we take?

2024-05-10 06:40 UTC, miqo1385 commented
the format seems correct, looks good to me

2024-05-15 04:29 UTC, kaimanasse15 commented
The Title looks good but I wonderd if anything is wrong with the database?
![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/91504156/3cbf7d84-208a-429f-8ff2-bdf0ecf37400)

2024-06-04 18:45 UTC, taylorpapke commented
Closing due to inactivity. Reopen if needed.

2024-06-04 18:45 UTC, closed without merging