NSC_Events for Roleauthorized my-events page
SeattleColleges/nsc-events-nextjs pull request #382
Opened 2024-05-30 16:28 UTC by kaimanasse15

issue: #375
Only the admin can get into this page to see the content

2024-05-30 16:46 UTC, heosman approved these changes
LGTM! There are some branch conflicts you need to resolve, though.
<img width="1120" alt="image" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/77591083/cd5eb7d2-94c1-4070-9b55-5e8c2f574fac">

2024-05-30 19:31 UTC, cshimm commented
Looks good to me I saw the Unauthorized page when I was logged out and the My Events page when I was logged in. The conflicts don't look too complex but let me know if you need help resolving them!

2024-05-30 21:12 UTC, JesseCaddell approved these changes
Looks good to me. Works as intended. As the others have mentioned just some conflicts that need to be resolved!
![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/80575182/cfe9073d-05f5-4a27-b582-fc5da2da5cea)

2024-05-31 03:51 UTC, kaimanasse15 commented
> Looks good to me I saw the Unauthorized page when I was logged out and the My Events page when I was logged in. The conflicts don't look too complex but let me know if you need help resolving them!

Hi @cshimm, I am wordering what is the conflict? So many projects are going for me that's why I am not sure which one. Thank you.

2024-05-31 05:06 UTC, Ali-7s approved these changes
LGTM.

<img width="805" alt="image" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/22021615/c77eab88-8651-4fbd-b240-eced0694d9e4">


There seems to be a simple ESLint error though, create-events page is missing a bracket at the end.

<img width="319" alt="image" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/22021615/a1b1b933-d1ef-400f-977e-faab012503ed">

2024-05-31 05:28 UTC, IsaacJrTypes reviewed
Double check your merge commit. I am getting errors in create-event page
![CleanShot 2024-05-30 at 22 26 52@2x](https://github.com/SeattleColleges/nsc-events-nextjs/assets/36749051/d5a46dab-3c41-4f64-b406-0c5d0f845dbf)

2024-05-31 05:28 UTC, IsaacJrTypes commented on app/create-event/page.tsx
> +
Hi Kai, can you explain your reasoning for leaving this condition statement empty?

2024-05-31 05:28 UTC, IsaacJrTypes commented on components/UnauthorizedPages.tsx
Nice job on isolating the box component into a separate component.  I would rename the component to UnauthorizedPageBox or UnauthorizedPageMessage, so it's clear what's in the component.

2024-05-31 06:18 UTC, heosman requested changes
Like others have mentioned, the condition statement is empty and the `UnauthorizedPages` component is unused on the Create Event page so I am still able to access the page as a non-admin and non-creator user. There is also a missing curcly brace and semicolon before the export statement at the end of the Create Event file. 

I think it would be great to implement @IsaacJrTypes's suggestion for clarity purposes.

2024-05-31 06:30 UTC, kaimanasse15 commented
@heosman I tried to fix it again. Please help me to double check on it. Thank you

2024-05-31 09:54 UTC, bennettsf commented
I feel like it would be nice if you were consistent with how you implement the role checking. 

Maybe do the same thing you did in 'my-events' for 'create-event' where it's just **one return with an if else statement** rather than an isolated if statement:

![uOstDLY (1)](https://github.com/SeattleColleges/nsc-events-nextjs/assets/33855430/d761bf41-79f4-47d2-914b-f4181ea6130f)


Other than that and following Isaac's suggestion to rename the component, everything looks good!

2024-06-01 02:43 UTC, cshimm commented
> > Looks good to me I saw the Unauthorized page when I was logged out and the My Events page when I was logged in. The conflicts don't look too complex but let me know if you need help resolving them!
> 
> Hi @cshimm, I am wordering what is the conflict? So many projects are going for me that's why I am not sure which one. Thank you.

if you go to the bottom of the page you should see a message notifying you about conflicts with 'main'
![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/13278479/a66981ab-f128-449b-9242-8010d9ef7c64)

if you click that you'll be brought to a basic text editor that shows the code for the file with conflict and 2 blocks of code wrapped with a red line. 
![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/13278479/f4c24687-b676-4c54-bd00-a2942324d535)

These blocks of code are in different branches and are conflicting with each other, so they'll need to be merged manually. You'll need to go through both blocks carefully, including your changes from your branch and avoiding overwriting or deleting any code from 'main'.

2024-06-01 03:25 UTC, heosman commented
> @heosman I tried to fix it again. Please help me to double check on it. Thank you

@kaimanasse15 I've tested your PR again and there are still some things you need to fix. 
I am experiencing a compile error because of the missing curly brace before the export statement. Here is how you would fix that:
<img width="214" alt="image" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/77591083/4269c622-61c5-447c-8d80-af4105b1bbc5">

The conditions in the if-else statements on the My Events page and Create Event are different, but that shouldn't be the case. Because of the incorrect `if` condition and the lack of the `else` statement, which should be returning the Unauthorized page, the Create Event page is still displaying for unauthorized users. Like @bennettsf mentioned, being consistent with the conditional logic and re-using the Unauthorizedpages component the same way you did on the My Event page should simplify things.  You should also check out @cshimm's instructions of how to resolve the branch conflicts.

2024-06-01 03:29 UTC, kaimanasse15 commented
> > @heosman I tried to fix it again. Please help me to double check on it. Thank you
> 
> @kaimanasse15 I've tested your PR again and there are still some things you need to fix. I am experiencing a compile error because of the missing curly brace before the export statement. Here is how you would fix that: <img alt="image" width="214" src="https://private-user-images.githubusercontent.com/77591083/335774095-4269c622-61c5-447c-8d80-af4105b1bbc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMTI3OTQsIm5iZiI6MTcxNzIxMjQ5NCwicGF0aCI6Ii83NzU5MTA4My8zMzU3NzQwOTUtNDI2OWM2MjItNjFjNS00NDdjLThkODAtYWY0MTA1YjFiYmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDAzMjgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMzQzNjNmMmQ4M2VkZWY4M2U4MTNjZDMwNGNmYzFlNTA1ZTk5MmYyZDJiOWQ3YjUxNzZjMjc4MWE1ZDYwODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HUUeHqA1DcQIFWs-R4DFIOeJJ30r5a2XveIYe5JyJ7Y">
> 
> The conditions in the if-else statements on the My Events page and Create Event are different, but that shouldn't be the case. Because of the incorrect `if` condition and the lack of the `else` statement, which should be returning the Unauthorized page, the Create Event page is still displaying for unauthorized users. Like @bennettsf mentioned, being consistent with the conditional logic and re-using the Unauthorizedpages component the same way you did on the My Event page should simplify things. You should also check out @cshimm's instructions of how to resolve the branch conflicts.

Yeah it showed error when I add one more in. May you passed the full code for me on Slack? Thanks, @heosman

2024-06-01 03:40 UTC, heosman commented
>
> 
> Yeah it showed error when I add one more in. May you passed the full code for me on Slack? Thanks, @heosman
I sent you the code with the curly brace added in on Slack.

2024-06-07 20:20 UTC, taylorpapke commented
> @kaimanasse15 I sent you the code with the curly brace added in on Slack.

Hey @heosman, there's been no activity on this PR since you commented a week ago. Do you mind pushing the fix you have to this PR so we can get it merged in?

2024-06-07 23:22 UTC, heosman approved these changes

2024-06-07 23:32 UTC, merged