_nsc-event-nextjs_sprint6_#285_nav_bar_signout_button
SeattleColleges/nsc-events-nextjs pull request #395
Opened 2024-06-01 05:06 UTC by miqo1385

Please fill out this description with the following:
Resolves <issue #285 >

https://github.com/SeattleColleges/nsc-events-nextjs/assets/97195623/4de46263-9336-411e-9f45-04203579bf2b

I fix the sign out button, however when click in the profile I'm not sure is redirecting correctly to either Admin or Creator. I would be super appreciated if somebody can give me a hand with that.

2024-06-05 05:20 UTC, taylorpapke requested changes
It looks like the functionality is working properly for the dropdown. It routes to admin/creator pages and signs outs as expected. However, we've lost event loading on this branch and there are some UI design changes to the nav bar that I believe to be outside the scope of this issue.

2024-06-07 04:19 UTC, miqo1385 commented on components/Navbar.tsx
> +                  <Link href={profileLink()} passHref>
it was fixed.

2024-06-07 04:23 UTC, miqo1385 commented
NSC white logo added. I change Profile for My Account

https://github.com/SeattleColleges/nsc-events-nextjs/assets/97195623/2cdd55eb-68d2-4eaf-8f68-10dc40541775

2024-06-07 06:34 UTC, heosman commented
@miqo1385 I looked over your changes on this PR again and it looks like the profile dropdown is working properly. I am routed to the appropriate pages when signed in as a admin or creator. Something you should know is that the white NSC logo has already been added to the nav bar on the main branch.

Like @taylorpapke mentioned, the events are not loading when using the NSC API URL. 
<img width="750" alt="image" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/77591083/c0683e43-5391-4b97-a13d-bc1f0ab4218f">

The "Event" link on the nav bar is causing an error because it is routing to the Event Detail page instead of the Home page. The Sign In link should still be visible on the bar when not signed in. The "My Account" link should not be appearing in the profile dropdown for normal users. The profile dropdown icon also needs to be updated, and the "NSC" link next to the NSC Logo should be removed, as I have mentioned before.

2024-06-08 20:18 UTC, taylorpapke commented
@miqo1385 I think the problem here is that you are using a very old branch. I believe the best course of action would be to create a new branch from main and copy over the changes you want from this PR.

2024-06-11 05:53 UTC, MaddasaHatter commented
Still seeing some conflicts and failed checks. I am also having the same issues as stated above so I am assuming you haven't had the chance to make the requested changes yet.

2024-06-11 05:54 UTC, MaddasaHatter commented
Still seeing some conflicts and failed checks. I am also having the same issues as stated above so I am assuming you haven't had the chance to make the requested changes yet.
![Screenshot 2024-06-10 225411](https://github.com/SeattleColleges/nsc-events-nextjs/assets/52189566/ca48195d-10d0-4b28-b439-b8ad4f63e796)

2024-06-12 03:38 UTC, Robel-003 reviewed
I'm able to sign out but when I click "My Account" link in the dropdown, I'm routed to the dashboard.

https://github.com/SeattleColleges/nsc-events-nextjs/assets/116779961/4e1d4efd-33f5-483d-9070-e92459181c63

2024-06-26 08:42 UTC, closed without merging