updating_patch_dependencies_only_sprint14_#572_PR
SeattleColleges/nsc-events-nextjs pull request #573
Opened 2024-11-12 04:23 UTC by miqo1385

This is a pull request!

Please use the following format for the title:
< repo > _ < sprint > _ < issue > _ < pr or issue name >

Please fill out this description with the following:
Resolves issue #572 

It was more challenging than we anticipated the last time we attempted to update the dependencies in these projects. and it appears that the job was put on hold. In order to begin moving cautiously with minor and big upgrades, I started small by changing the patch dependencies alone.
These dependencies (minor and major) need to be updated following patch updates.

![image](https://github.com/user-attachments/assets/4306f2a1-892b-43ec-ae9c-0f43866bdfaa)

2024-11-13 08:04 UTC, el-riber approved these changes
here it worked very well! good job
<img width="1440" alt="Screenshot 2024-11-13 at 12 03 30 AM" src="https://github.com/user-attachments/assets/78c688a9-8e54-4936-8230-516c989432c3">

2024-11-14 06:28 UTC, nhapham03 commented
![image](https://github.com/user-attachments/assets/b04aef99-dc15-4bc9-a4ae-4be05b2e340d)
Works on my end. LGTM!

2024-11-14 06:53 UTC, Asfand00 requested changes
Looks good on my end, didn't run into any issues when testing or running the server as a test.
![nsc-events-dependecy-update-test](https://github.com/user-attachments/assets/803cd8d1-1c19-486e-aa4c-6f02d8b6956e)

You seem to have a check that is still pending for `on pull request / build-and-test Expected` part. I'm not too familiar with CI/CD stuff but I did check your .yml file for on pull request in the github workflow section and the set_status_check section is commented out. That might possibly be the issue but just guessing here, maybe try uncommenting that section to see if that fixes the issue. Otherwise, it might be another CI/CD issue. Not safe to approve yet until check is completed. I'll try to help as best I can if you need it @miqo1385.

2024-11-14 22:57 UTC, JesseCaddell requested changes
In regards to the on pull request / build-and-test CI issue... I just updated the CI/CD actions yesterday. This should solve our problem. For some reason the action was not triggering. The only solution I have found so far is to make a new PR and see if it triggers. I was able to merge my changes without the build-and-test yesterday, so I'll request a second set of eyes in regards to that @bcko @taylorpapke but I am going to approve this PR once it is up to date with main! Looks good, thank you for your hard work!

2024-11-15 01:38 UTC, el-riber approved these changes

2024-11-17 17:37 UTC, Diego-Cano commented
Great work on the patch dependency updates! Everything looks good and runs smoothly on my end without any issues during testing. The updates are well-organized and keep things clean while addressing the patch updates effectively. I did notice that the "build-and-test" CI step is still pending. It might be worth taking another look at the .yml file, specifically the commented-out set_status_check section, to see if re-enabling that resolves the problem.

Overall, I think this is a solid update, and once the CI step is sorted, it should be good to go. Also, I found a helpful link about handling dependency updates or similar workflows  : [Semantic Versioning Guide](https://semver.org/) for some helpful tips and best practices.

<img width="1712" alt="Screenshot 2024-11-17 at 9 29 58 AM" src="https://github.com/user-attachments/assets/c5a01d5c-1ce8-451a-9954-0e8393629a9f">

2025-01-13 21:10 UTC, closed without merging